GRANT ALL ON INSIS_SYS_V10.SYSTEM_PERIODS       TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_SYS_V10.GVAR_SYS             TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_IODATA.ERROR_HANDLING_FILE_PKG TO INSIS_CUST_ADDON;


GRANT ALL ON INSIS_GEN_V10.POLICY_PARTICIPANTS       TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_SYS_V10.SRV_SYSTEM_PARAMS         TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_SYS_V10.SRV_PRM_POLICY            TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_SYS_V10.SRVERRMSG                 TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_BLC_V10.BLC_PAY_INSTRUMENTS   TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_V10.POLICY_ENGAGEMENT_BILLING TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_V10.BLC_POLICY_PAYMENT_PLAN   TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_CFG_V10.CFG_NL_PRODUCT_TEXT   TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_BLC_V10.BLC_DOCUMENTS         TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_BLC_V10.BLC_ITEMS             TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_BLC_V10.BLC_ACCOUNTS          TO INSIS_CUST_ADDON;
GRANT ALL ON INSIS_GEN_BLC_V10.BLC_LOG_PKG           TO INSIS_CUST_ADDON;

GRANT SELECT ON INSIS_GEN_BLC_V10.BLC_PAYMENTS     TO INSIS_CUST_ADDON;
GRANT SELECT ON INSIS_GEN_BLC_V10.BLC_TRANSACTIONS TO INSIS_CUST_ADDON;
GRANT SELECT ON INSIS_GEN_BLC_V10.BLC_PAY_RUN      TO INSIS_CUST_ADDON;
GRANT SELECT ON INSIS_GEN_BLC_V10.BLC_INSTALLMENTS TO INSIS_CUST_ADDON;
GRANT SELECT ON INSIS_GEN_V10.H_INSR_TYPE          TO INSIS_CUST_ADDON; 
GRANT SELECT ON INSIS_GEN_V10.H_INSR_TYPE          TO INSIS_CUST_ADDON;
